### PR TITLE
removed commented code and cleaned obsolete implementation of convolutio...

### PR DESCRIPTION
**Pull request by psteinb**
...n3DfftCUDA w/o kernelDim parameter
@StephanPreibisch: this is more a maintenance commit than anything else, I wonder if convolution3DfftCUDA is needed at all anymore?

### CODE REVIEW

**Comment by psteinb** [comment]
@StephanPreibisch: if this is merged, I have 1-2 more performance improvements that I can apply

**Comment by StephanPreibisch** [comment]
Hi @psteinb, I do not really want to remove this code as it is used for testing in some of the Java code we once wrote ...

**Comment by psteinb** [comment]
Ok, then we leave it. But I'd recommend not to dublicate 
implementations. I'll update this PR then.

**Comment by psteinb** [comment]
I updated the PR ... just to clearify: you call code that is commented out in the library from Java? Note that the library API remained intact, I just removed the dublicate implementation of 

```
imageType* convolution3DfftCUDA(imageType* im,int* imDim,imageType* kernel,int devCUDA){
// a lot of code
}{
```

and replaced it with 

```
imageType* convolution3DfftCUDA(imageType* im,int* imDim,imageType* kernel,int devCUDA)
{
  return convolution3DfftCUDA(im,imDim,kernel,imDim,devCUDA);
}
```

**Pull request closed without merging**
